import type { Config } from "tailwindcss"

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1.5rem",
        md: "3rem",
      },
      screens: {
        "2xl": "1920px",
      },
    },
    extend: {
      colors: {
        surface: "#fcf9f8",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdcc1",
        "inverse-primary": "#fcb97d",
        background: "#fcf9f8",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-container": "#24201c",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "outline-variant": "#c4c7c7",
        "on-error-container": "#93000a",
        "surface-variant": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#2e1500",
        "surface-bright": "#fcf9f8",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#636262",
        "secondary-container": "#e2dfde",
        "primary-fixed-dim": "#fcb97d",
        "on-primary-container": "#b67c46",
        "inverse-surface": "#313030",
        "tertiary-fixed-dim": "#cec5be",
        "primary-container": "#361a00",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#eae1da",
        "on-tertiary-fixed": "#1f1b17",
        "surface-tint": "#855321",
        error: "#ba1a1a",
        "surface-container": "#f0eded",
        secondary: "#5f5e5e",
        tertiary: "#0d0906",
        "on-error": "#ffffff",
        "on-background": "#1c1b1b",
        "surface-container-highest": "#e5e2e1",
        "on-tertiary-container": "#8e8781",
        "on-tertiary-fixed-variant": "#4b4641",
        outline: "#747878",
        "on-secondary-fixed-variant": "#474746",
        primary: "#140700",
        "on-primary-fixed-variant": "#693c0a",
        "surface-dim": "#dcd9d9",
        "on-surface": "#1c1b1b",
        "surface-container-low": "#f6f3f2",
        "on-surface-variant": "#444748",
        "surface-container-high": "#eae7e7",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "0px",
      },
      boxShadow: {
        hairline: "0 1px 0 rgba(20, 7, 0, 0.08)",
        architectural: "0 24px 80px rgba(20, 7, 0, 0.10)",
      },
      fontFamily: {
        headline: ["Futura PT", "Futura", "sans-serif"],
        body: ["Futura PT", "Futura", "sans-serif"],
        label: ["Futura PT", "Futura", "sans-serif"],
      },
      letterSpacing: {
        section: "0.28em",
      },
    },
  },
  plugins: [],
} satisfies Config
